# Generated by Django 4.1.5 on 2023-02-06 00:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apka', '0005_remove_profile_data_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_data',
            new_name='Profile',
        ),
    ]
